# Generated by Django 4.2.3 on 2026-03-31 08:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target_muscle', models.CharField(choices=[('C', 'Chest'), ('T', 'Triceps'), ('S', 'Shoulders'), ('Abs', 'Abs'), ('B', 'Biceps'), ('Fr', 'Forearms'), ('UB', 'UpperBack'), ('L', 'Lats'), ('H', 'Hamstrings'), ('Q', 'Quadriceps'), ('Ca', 'Calves'), ('G', 'Glutes'), ('Tr', 'Traps'), ('N', 'Neck'), ('LB', 'LowerBack')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2026, 3, 31, 8, 6, 43, 579493, tzinfo=datetime.timezone.utc), verbose_name='Workout Date')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PotentialUnleashed.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PotentialUnleashed.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps_target', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Rep Target')),
                ('reps_hit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Reps Hit')),
                ('rest_time', models.IntegerField(default=60, verbose_name='Rest')),
                ('weight_target', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Weight Target (Kgs)')),
                ('weight_hit', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Weight Hit (Kgs)')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PotentialUnleashed.workoutexercise')),
            ],
        ),
    ]
