# Generated by Django 4.2.3 on 2026-03-31 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 31, 8, 19, 15, 825630, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
