# Generated by Django 4.2.3 on 2026-04-06 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0002_workout_name_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 6, 17, 34, 25, 756929, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workoutexercises', to='PotentialUnleashed.workout'),
        ),
    ]
