# Generated by Django 4.2.3 on 2026-04-08 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0003_alter_workout_date_alter_workoutexercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 8, 19, 52, 33, 986090, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
