# Generated by Django 4.2.3 on 2026-04-16 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0010_alter_workout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Please Add Name', max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 16, 12, 40, 0, 28854, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutexercises', to='PotentialUnleashed.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='mesocycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='PotentialUnleashed.mesocycle'),
        ),
    ]
