# Generated by Django 4.2.3 on 2026-04-17 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0011_mesocycle_alter_workout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 17, 12, 51, 48, 101467, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
