# Generated by Django 4.2.3 on 2026-04-17 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0012_alter_exercise_name_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 17, 12, 53, 16, 610691, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
