# Generated by Django 4.2.3 on 2026-04-18 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0013_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('U', 'Upper'), ('L', 'Lower'), ('P', 'Push'), ('PU', 'Pull'), ('LE', 'Legs'), ('A', 'Arms'), ('FB', 'FullBody'), ('C', 'Cardio'), ('N', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 18, 13, 5, 19, 956451, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
