# Generated by Django 4.2.3 on 2026-04-20 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0014_workout_type_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 10, 43, 1, 301052, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
