# Generated by Django 4.2.3 on 2026-08-02 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0015_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='progression_model',
            field=models.CharField(choices=[('SS', 'Approach: all sets besides last set are done at rep target'), ("3's", 'Approach: Pick 2 or 3 sets, with a weight you can do 7-8reps with. When you Perform 8+, add minimum Weight.'), ('DDP', 'Approach: 3 total sets, each progress at the own pace. (Compounds)'), ('Rep Goal', 'Approach: Use the same weight for each set, all sets taken to max safe reps, Add up total reps, If reps >=  a predefined rep goal, add weight'), ('Bulldozer', 'Approach: Take 3 sets into 5 mini sets'), ('N', 'None')], default='SS', max_length=500),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 2, 16, 33, 11, 485889, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
