# Generated by Django 4.2.3 on 2026-08-26 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotentialUnleashed', '0016_set_progression_model_alter_workout_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['workout_exercise__workout__date']},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['workout__date']},
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 26, 11, 53, 30, 957996, tzinfo=datetime.timezone.utc), verbose_name='Workout Date'),
        ),
    ]
